### ISSUE TITLE
I clone app in STS and try to run the app and found the error below

### ISSUE THREAD

**Issue by samism91** [vahidhedayati/kchat#1]
Error |
2015-07-01 12:11:48,046 [localhost-startStop-1] ERROR spi.SqlExceptionHelper  - Table "AUTH_PROVIDER" not found; SQL statement:
select this_.id as id1_1_0_, this_.version as version2_1_0_, this_.friendly_name as friendly3_1_0_, this_.name as name4_1_0_ from auth_provider this_ where (this_.name=? and this_.friendly_name=?) limit ? [42102-176]
Error |
2015-07-01 12:11:48,078 [localhost-startStop-1] ERROR context.GrailsContextLoaderListener  - Error initializing the application: Hibernate operation: could not prepare statement; bad SQL grammar [select this_.id as id1_1_0_, this_.version as version2_1_0_, this_.friendly_name as friendly3_1_0_, this_.name as name4_1_0_ from auth_provider this_ where (this_.name=? and this_.friendly_name=?) limit ?]; nested exception is org.h2.jdbc.JdbcSQLException: Table "AUTH_PROVIDER" not found; SQL statement:
select this_.id as id1_1_0_, this_.version as version2_1_0_, this_.friendly_name as friendly3_1_0_, this_.name as name4_1_0_ from auth_provider this_ where (this_.name=? and this_.friendly_name=?) limit ? [42102-176]
Message: Hibernate operation: could not prepare statement; bad SQL grammar [select this_.id as id1_1_0_, this_.version as version2_1_0_, this_.friendly_name as friendly3_1_0_, this_.name as name4_1_0_ from auth_provider this_ where (this_.name=? and this_.friendly_name=?) limit ?]; nested exception is org.h2.jdbc.JdbcSQLException: Table "AUTH_PROVIDER" not found; SQL statement:
select this_.id as id1_1_0_, this_.version as version2_1_0_, this_.friendly_name as friendly3_1_0_, this_.name as name4_1_0_ from auth_provider this_ where (this_.name=? and this_.friendly_name=?) limit ? [42102-176]
    Line | Method
->>  622 | findWhere                        in org.grails.datastore.gorm.GormStaticApi

---

|    669 | internalFindOrCreate             in     ''
|    665 | findOrSaveWhere . . . . . . . .  in     ''
|     11 | doCall                           in BootStrap$_closure1
|    327 | evaluateEnvironmentSpecificBlock in grails.util.Environment
|    320 | executeForEnvironment            in     ''
|    296 | executeForCurrentEnvironment . . in     ''
|    262 | run                              in java.util.concurrent.FutureTask
|   1145 | runWorker . . . . . . . . . . .  in java.util.concurrent.ThreadPoolExecutor
|    615 | run                              in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run . . . . . . . . . . . . . .  in java.lang.Thread
Caused by JdbcSQLException: Table "AUTH_PROVIDER" not found; SQL statement:
select this_.id as id1_1_0_, this_.version as version2_1_0_, this_.friendly_name as friendly3_1_0_, this_.name as name4_1_0_ from auth_provider this_ where (this_.name=? and this_.friendly_name=?) limit ? [42102-176]
->>  344 | getJdbcSQLException              in org.h2.message.DbException

---

|    178 | get                              in     ''
|    154 | get . . . . . . . . . . . . . .  in     ''
|   5213 | readTableOrView                  in org.h2.command.Parser
|   1220 | readTableFilter . . . . . . . .  in     ''
|   1859 | parseSelectSimpleFromPart        in     ''
|   1968 | parseSelectSimple . . . . . . .  in     ''
|   1853 | parseSelectSub                   in     ''
|   1674 | parseSelectUnion . . . . . . . . in     ''
|   1662 | parseSelect                      in     ''
|    434 | parsePrepared . . . . . . . . .  in     ''
|    306 | parse                            in     ''
|    278 | parse . . . . . . . . . . . . .  in     ''
|    243 | prepareCommand                   in     ''
|    442 | prepareLocal . . . . . . . . . . in org.h2.engine.Session
|    384 | prepareCommand                   in     ''
|   1188 | prepareCommand . . . . . . . . . in org.h2.jdbc.JdbcConnection
|     73 | <init>                           in org.h2.jdbc.JdbcPreparedStatement
|    276 | prepareStatement . . . . . . . . in org.h2.jdbc.JdbcConnection
|    622 | findWhere                        in org.grails.datastore.gorm.GormStaticApi
|    669 | internalFindOrCreate . . . . . . in     ''
|    665 | findOrSaveWhere                  in     ''
|     11 | doCall . . . . . . . . . . . . . in BootStrap$_closure1
|    327 | evaluateEnvironmentSpecificBlock in grails.util.Environment
|    320 | executeForEnvironment . . . . .  in     ''
|    296 | executeForCurrentEnvironment     in     ''
|    262 | run . . . . . . . . . . . . . .  in java.util.concurrent.FutureTask
|   1145 | runWorker                        in java.util.concurrent.ThreadPoolExecutor
|    615 | run . . . . . . . . . . . . . .  in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run                              in java.lang.Thread
Error |
Forked Grails VM exited with error

**Comment by vahidhedayati** [comment]
This app relies on internal LDAP / AD for authentication .

Take a look here : 

https://github.com/vahidhedayati/kchat/blob/master/grails-app/conf/BootStrap.groovy

AND 

https://github.com/vahidhedayati/kchat/blob/master/grails-app/conf/kchatConfig.groovy#L55-L65

As well as :

https://github.com/vahidhedayati/kchat/blob/master/grails-app/conf/create-db.sql

Also ensure you have configured  serverurl:

 JAVA_OPTS="$JAVA_OPTS -DSERVERURL=$HOSTNAME"

Do you really expect to be able to clone an application defined and configured for a specific environment organisation and for it to work without having to modify or reconfigure any of its components ?
